# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: ikalnytskyi/action-setup-postgres@v6
      with:
        username: postgres
        password: www@ms.com
        database: ZackShop
        port: 34837
        postgres-version: "16"
        ssl: "on"
      id: postgres
    - name: Build
      run: dotnet build ./ZackShop.BackEnd
    - name: Test
      run: dotnet test ./ZackShop.BackEnd
    - name: Install Styker
      run: dotnet tool install -g dotnet-stryker
    - name: Stryker
      run: |
          cd ZackShop.BackEnd          
          dotnet stryker --config-file=UsersDomain.Shared.UnitTests/stryker-config.json
          dotnet stryker --config-file=AuthOpenAPIs.UnitTests/stryker-config.json


          